version: '3'
services:
  app:
    container_name: work
    restart: always
    build: .
    ports:
      - '80:3000'

  api:
        container_name: api
        build: ./dbserver/
        ports: 
          - '8080:8080'

